    Data Manipulation and Analysis with Pandas:
Data manipulation and analysis are key tasks in any data science or data analysis project. Pandas provides a wide range of functions for data manipulation and analysis, making it easier to clean, transform, and extract insights from data. In this lesson, we will cover various data manipulation and analysis techniques using Pandas.

In [13]:
import pandas as pd

In [14]:
df=pd.read_csv('Netflix Dataset.csv')

In [19]:
df.head(5)

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,07:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",PG-13,123 min,Dramas,A brilliant group of students become card-coun...

In [20]:
df.tail()

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description
7784,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...
7785,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...
7786,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast..."
7787,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...
7788,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...

In [21]:
df.describe()

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description
count,7789,7789,7789,5401,7071,7282,7779,7782,7789,7789,7789
unique,7787,2,7787,4050,6831,681,1565,14,216,492,7769
top,s684,Movie,Backfire,"Raúl Campos, Jan Suter",David Attenborough,United States,"January 1, 2020",TV-MA,1 Season,Documentaries,Multiple women report their husbands as missin...
freq,2,5379,2,18,18,2556,118,2865,1608,334,3

In [22]:
df.dtypes

Show_Id         object
Category        object
Title           object
Director        object
Cast            object
Country         object
Release_Date    object
Rating          object
Duration        object
Type            object
Description     object
dtype: object

In [23]:
## Handling Missing Values
df.isnull().any()

Show_Id         False
Category        False
Title           False
Director         True
Cast             True
Country          True
Release_Date     True
Rating           True
Duration        False
Type            False
Description     False
dtype: bool

In [24]:
df.isnull().sum()

Show_Id            0
Category           0
Title              0
Director        2388
Cast             718
Country          507
Release_Date      10
Rating             7
Duration           0
Type               0
Description        0
dtype: int64

In [25]:
df_filled=df.fillna(0)

In [27]:
df.isnull().values.any()

np.True_

In [ ]:
df.sort_values("Release_Date", ascending=False).head(10)

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description
6885,s6884,Movie,The Social Dilemma,Jeff Orlowski,"Skyler Gisondo, Kara Hayward, Vincent Kartheiser",United States,"September 9, 2020",PG-13,94 min,Documentaries,This documentary-drama hybrid explores the dan...
1217,s1218,Movie,Cargo,Arati Kadav,"Vikrant Massey, Shweta Tripathi, Nandu Madhav,...",India,"September 9, 2020",TV-14,113 min,"Comedies, Dramas, Independent Movies",Aboard a spaceship where souls of the deceased...
5686,s5686,Movie,So Much Love to Give,Marcos Carnevale,"Adrián Suar, Soledad Villamil, Gabriela Toscan...",Argentina,"September 9, 2020",TV-14,108 min,"Comedies, International Movies, Music & Musicals",Fernando is a family man — equally committed t...
1559,s1560,Movie,Cuties,Maïmouna Doucouré,"Fathia Youssouf, Médina El Aidi-Azouni, Esther...",France,"September 9, 2020",TV-MA,96 min,"Dramas, International Movies",Eleven-year-old Amy starts to rebel against he...
3496,s3497,TV Show,La Línea: Shadow of Narco,Pepe Mora,NaN,Spain,"September 9, 2020",TV-MA,1 Season,"Crime TV Shows, Docuseries, International TV S...","A stone's throw from Africa, the Spanish beach..."
2385,s2386,TV Show,Get Organized with The Home Edit,NaN,NaN,United States,"September 9, 2020",TV-PG,1 Season,Reality TV,Expert home organizers Clea and Joanna help ce...
4509,s4510,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
5587,s5587,TV Show,Show Me the Money,NaN,"Afdlin Shauki, Patrick Teoh, Mano Maniam, Rash...",NaN,"September 9, 2018",TV-14,2 Seasons,"International TV Shows, TV Comedies",Four ordinary family members find their lives ...
3121,s3122,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2295,s2296,Movie,From Paris with Love,Pierre Morel,"John Travolta, Jonathan Rhys Meyers, Kasia Smu...","France, United Kingdom, United States","September 8, 2020",R,93 min,"Action & Adventure, International Movies",A low-level intelligence agent gets pulled int...

In [33]:
df.duplicated().sum()          # how many duplicate rows

np.int64(2)

In [37]:
df.sort_values("Release_Date").head(1)    # oldest show/movie

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description
6673,s6672,TV Show,The Minimighty Kids,NaN,NaN,France,"April 15, 2018",TV-G,2 Seasons,"Kids' TV, TV Comedies","Some have big feet or a sniffly nose, others a..."

In [ ]:
df.sort_values("Release_Date").tail(1)    # newest show/movie

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description
6066,s6066,TV Show,The Adventures of Figaro Pho,NaN,"Luke Jurevicius, Craig Behenna, Charlotte Haml...",Australia,NaN,TV-Y7,2 Seasons,"Kids' TV, TV Comedies","Imagine your worst fears, then multiply them: ..."